name: CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run component tests
        uses: cypress-io/github-action@v4
        with:
          component: true

      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: npm start
          wait-on: "http://localhost:3000"
